version: "3.8"

services:
  backend:
    build: ./
    ports:
      - 9000:9000
    environment:
      DB_CONN: mongodb://db:27017/building
    volumes:
      - ./:/app
    depends_on:
      - db
    command: ./docker-entrypoint.sh
    links:
      - db

  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - building:/data/db

volumes:
  tftesh:
